In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [5]:
np.linspace(1,10,40)

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

In [8]:
arrayCentena=np.linspace(1,10,100)

In [9]:
arrayCentena

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [16]:
arrayCentena.shape


(100,)

In [20]:
arrayCentena.min()


1.0

In [21]:
arrayCentena.max()


10.0

In [22]:
arrayCentena.sum()

550.0